debug: true

inverter:
  path: /dev/hidraw0

mqtt:
  host: localhost
  port: 1883
  username: mpqtt
  password: mpqtt
  client_id: mpqtt
  topic: mpqtt/status
  discovery:
    enabled: true
    prefix: homeassistant
    node_name: mpqtt
    device_name: MPQTT
    device_id: mpqtt
